/** @type {import('tailwindcss').Config} */
export default {
	content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
	theme: {
		typography: (theme) => ({
			DEFAULT: {
				css: {
					maxWidth: "none",
					h1: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "3.375rem",
						lineHeight: "1!important",
						fontWeight: "400",
						color: theme("colors.textColor"),
					},
					h2: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "3rem",
						lineHeight: "1!important",
						fontWeight: "400",
						color: theme("colors.textColor"),
					},
					h3: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "2.625rem",
						lineHeight: "1.125!important",
						fontWeight: "400",
						color: theme("colors.textColor"),
					},
					h4: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "2.25rem",
						lineHeight: "1.25!important",
						fontWeight: "400",
						color: theme("colors.textColor"),
					},
					h5: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "2rem",
						lineHeight: "1.5!important",
						fontWeight: "400",
						color: theme("colors.textColor"),
					},
					h6: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "1.5rem",
						lineHeight: "1.5!important",
						fontWeight: "400",
						color: theme("colors.textColor"),
					},
					p: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "1.125rem",
						lineHeight: "1.5!important",
						color: theme("colors.textColor"),
					},
					a: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "1.125rem",
						lineHeight: "1.5!important",
						textDecoration: "none",
						position: "relative",
						display: "inline-block",
						transition: "color 0.2s",
						color: theme("colors.main500"),
						"&:hover": {
							"&:before": {
								width: "100%",
							},
						},
						"&:before": {
							content: '""',
							position: "absolute",
							left: "0",
							bottom: "0",
							display: "block",
							height: "2px",
							width: "0",
							backgroundColor: theme("colors.main500"),
							transition: "width 0.2s",
						},
					},
					ul: {
						marginTop: "0!important",
						marginBottom: "0!important",
						display: "flex",
						flexDirection: "column",
						gap: "1rem",
						color: theme("colors.textColor"),
					},
					ol: {
						marginTop: "0!important",
						marginBottom: "0!important",
						display: "flex",
						flexDirection: "column",
						gap: "1rem",
						color: theme("colors.textColor"),
					},
					li: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "1.125rem",
						lineHeight: "1.5!important",
						paddingLeft: "0!important",
						color: theme("colors.textColor"),
						"&::marker": {
							color: "inherit!important",
						},
					},
					blockquote: {
						marginTop: "0!important",
						marginBottom: "0!important",
						fontSize: "1.25rem",
						lineHeight: "1.5!important",
						color: theme("colors.textColor"),
					},
					hr: {
						marginTop: "0!important",
						marginBottom: "0!important",
						backgroundColor: "rgba(0, 0, 0, 0.1)",
						border: "none",
						height: "1px",
						width: "100%",
					},
				},
			},
			white: {
				css: {
					color: "#FFFFFF",
					h1: { color: "#FFFFFF" },
					h2: { color: "#FFFFFF" },
					h3: { color: "#FFFFFF" },
					h4: { color: "#FFFFFF" },
					h5: { color: "#FFFFFF" },
					h6: { color: "#FFFFFF" },
					p: { color: "#FFFFFF" },
					li: { color: "#FFFFFF" },
					blockquote: { color: "#FFFFFF" },
					hr: { background: "rgba(255, 255, 255, 0.1)" },
				},
			},
			"2xl": {
				css: {
					h1: { fontSize: "3rem" },
					h2: { fontSize: "2.625rem" },
					h3: { fontSize: "2.25rem" },
					h4: { fontSize: "2rem" },
					h5: { fontSize: "1.5rem" },
					h6: { fontSize: "1.25rem" },
					p: { fontSize: "1.125rem" },
					a: { fontSize: "1.125rem" },
					li: { fontSize: "1.125rem" },
					blockquote: { fontSize: "1.25rem" },
				},
			},
			xl: {
				css: {
					h1: { fontSize: "2.625rem" },
					h2: { fontSize: "2.25rem" },
					h3: { fontSize: "1.5rem" },
					h4: { fontSize: "1.375rem" },
					h5: { fontSize: "1.25rem" },
					h6: { fontSize: "1.125rem" },
					p: { fontSize: "1.125rem" },
					a: { fontSize: "1.125rem" },
					ul: { gap: "0.75rem" },
					ol: { gap: "0.75rem" },
					li: { fontSize: "1.125rem" },
					blockquote: { fontSize: "1.125rem" },
				},
			},
			lg: {
				css: {
					h1: { fontSize: "2.25rem" },
					h2: { fontSize: "2rem" },
					h3: { fontSize: "1.5rem" },
					h4: { fontSize: "1.25rem" },
					h5: { fontSize: "1.125rem" },
					h6: { fontSize: "1rem" },
					p: { fontSize: "1rem" },
					a: { fontSize: "1rem" },
					li: { fontSize: "1rem" },
					blockquote: { fontSize: "1.125rem" },
				},
			},
			md: {
				css: {
					h1: { fontSize: "2rem" },
					h2: { fontSize: "1.5rem" },
					h3: { fontSize: "1.25rem" },
					h4: { fontSize: "1.125rem" },
					h5: { fontSize: "1rem" },
					h6: { fontSize: "0.875rem" },
					p: { fontSize: "0.875rem" },
					a: { fontSize: "0.875rem" },
					ul: { gap: "0.5rem" },
					ol: { gap: "0.5rem" },
					li: { fontSize: "0.875rem" },
					blockquote: { fontSize: "1rem" },
				},
			},
			sm: {
				css: {
					h1: { fontSize: "2rem" },
					h2: { fontSize: "1.5rem" },
					h3: { fontSize: "1.25rem" },
					h4: { fontSize: "1.125rem" },
					h5: { fontSize: "1rem" },
					h6: { fontSize: "0.875rem" },
					p: { fontSize: "0.875rem" },
					a: { fontSize: "0.875rem" },
					ul: { gap: "0.25rem" },
					ol: { gap: "0.25rem" },
					li: { fontSize: "0.875rem" },
					blockquote: { fontSize: "1rem" },
				},
			},
			xs: {
				css: {
					h1: { fontSize: "2rem" },
					h2: { fontSize: "1.5rem" },
					h3: { fontSize: "1.25rem" },
					h4: { fontSize: "1.125rem" },
					h5: { fontSize: "1rem" },
					h6: { fontSize: "0.875rem" },
					p: { fontSize: "0.875rem" },
					a: { fontSize: "0.875rem" },
					li: { fontSize: "0.875rem" },
					blockquote: { fontSize: "1rem" },
				},
			},
		}),

		extend: {},
	},
	plugins: [],
};
